services:

  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    command: agent -dev -client 0.0.0.0 -ui
    ports:
      - "8500:8500"   
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      retries: 5       

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  messages-service:
    build: ./messages-service
    environment:
      - SERVICE_PORT=6001       
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      consul:
        condition: service_healthy
    deploy:
      replicas: 3
    restart: on-failure

  facade-service:
    build: ./facade-service
    environment:
      - SERVICE_PORT=5000
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "5000:5000"
    restart: on-failure

  logging-service:
    build: ./logging-service
    environment:
      - SERVICE_PORT=5001
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      consul:
        condition: service_healthy
    deploy:
      replicas: 3              
    restart: on-failure


