version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  logging-service1:
    build: 
      context: ./logging-service
    container_name: logging-service1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC_NAME: "test-topic"
      CONSUMER_GROUP: "logging-group-1"
      LOGGING_SERVICE_PORT: 5001
    ports:
      - "5001:5001"

  logging-service2:
    build: 
      context: ./logging-service
    container_name: logging-service2
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC_NAME: "test-topic"
      CONSUMER_GROUP: "logging-group-2"
      LOGGING_SERVICE_PORT: 5002
    ports:
      - "5002:5002"

  logging-service3:
    build: 
      context: ./logging-service
    container_name: logging-service3
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC_NAME: "test-topic"
      CONSUMER_GROUP: "logging-group-3"
      LOGGING_SERVICE_PORT: 5003
    ports:
      - "5003:5003"

  messages-service1:
    build:
      context: ./messages-service
    container_name: messages-service1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC_NAME: "test-topic"
      CONSUMER_GROUP: "messages-group-1"
      MESSAGES_SERVICE_PORT: 6001
    ports:
      - "6001:6001"

  messages-service2:
    build:
      context: ./messages-service
    container_name: messages-service2
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC_NAME: "test-topic"
      CONSUMER_GROUP: "messages-group-2"
      MESSAGES_SERVICE_PORT: 6002
    ports:
      - "6002:6002"

  facade-service:
    build:
      context: ./facade-service
    container_name: facade-service
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - logging-service1
      - logging-service2
      - logging-service3
      - messages-service1
      - messages-service2
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC_NAME: "test-topic"
    ports:
      - "5000:5000"
    restart: always
